(window.webpackJsonp=window.webpackJsonp||[]).push([[4],{2881:function(s,a,n){s.exports={basic:n(3001)}},3001:function(s,a,n){s.exports={content:{"zh-CN":[["ul",["li",["p","\u5728antd.Button\u7EC4\u4EF6\u57FA\u7840\u4E0A\u5C01\u88C5, type\u5C5E\u6027\u503C\u589E\u52A0",["code","delete"],", \u5220\u9664\u6309\u94AE\u5F39\u7A97\u786E\u8BA4\u6846"]],["li",["p","\u517C\u5BB9",["a",{title:null,href:"https://ant.design/components/button-cn/"},"antd.Button"],"\u7EC4\u4EF6"]]]],"en-US":[]},meta:{order:0,title:{"zh-CN":"\u6309\u94AE\u4E8C\u6B21\u5C01\u88C5","en-US":"Type"},filename:"components/buttonpro/demo/basic.md",id:"components-buttonpro-demo-basic"},toc:["ul",["li",["a",{className:"bisheng-toc-h2",href:"#zh-CN",title:"zh-CN"},"zh-CN"]],["li",["a",{className:"bisheng-toc-h2",href:"#en-US",title:"en-US"},"en-US"]]],highlightedCode:["pre",{lang:"jsx",highlighted:`<span class="token keyword">import</span> <span class="token punctuation">{</span> message <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'antd'</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> ButtonPro <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pmbase'</span>

ReactDOM<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>ButtonPro</span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation">=</span><span class="token punctuation">"</span>delete<span class="token punctuation">"</span></span> <span class="token attr-name">onClick</span><span class="token script language-javascript"><span class="token punctuation">=</span><span class="token punctuation">{</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=</span><span class="token operator">></span> message<span class="token punctuation">.</span><span class="token function">success</span><span class="token punctuation">(</span><span class="token string">'\u5220\u9664\u6210\u529F'</span><span class="token punctuation">)</span><span class="token punctuation">}</span></span><span class="token punctuation">></span></span>\u5220\u9664<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>ButtonPro</span><span class="token punctuation">></span></span><span class="token punctuation">,</span>
  mountNode<span class="token punctuation">)</span><span class="token punctuation">;</span>`}],highlightedCodes:{jsx:`<span class="token keyword">import</span> <span class="token punctuation">{</span> message <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'antd'</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> ButtonPro <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pmbase'</span>

ReactDOM<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span>
  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span><span class="token class-name">ButtonPro</span></span> <span class="token attr-name">type</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>delete<span class="token punctuation">"</span></span> <span class="token attr-name">onClick</span><span class="token script language-javascript"><span class="token script-punctuation punctuation">=</span><span class="token punctuation">{</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> message<span class="token punctuation">.</span><span class="token function">success</span><span class="token punctuation">(</span><span class="token string">'\u5220\u9664\u6210\u529F'</span><span class="token punctuation">)</span><span class="token punctuation">}</span></span><span class="token punctuation">></span></span>\u5220\u9664<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span><span class="token class-name">ButtonPro</span></span><span class="token punctuation">></span></span><span class="token punctuation">,</span>
  mountNode<span class="token punctuation">)</span><span class="token punctuation">;</span>`},preview:function(){var t=n(0),c=n(48),p=n(57),o=n(2991);return t.createElement(o.ButtonPro,{type:"delete",onClick:function(){return p.message.success("\u5220\u9664\u6210\u529F")}},"\u5220\u9664")},style:`
.ant-popover-message {
  min-width: 200px;
  padding-bottom: 30px;
}
`}}}]);
