(window.webpackJsonp=window.webpackJsonp||[]).push([[10],{2887:function(s,a,n){s.exports={basic:n(3017)}},3017:function(s,a,n){s.exports={content:{"zh-CN":[["ul",["li",["p","\u6839\u636Eiconfont\u56FE\u6807\u5E93\u5C01\u88C5"]]]],"en-US":[]},meta:{order:0,title:{"zh-CN":"\u56FE\u6807","en-US":"Type"},filename:"components/iconpro/demo/basic.md",id:"components-iconpro-demo-basic"},toc:["ul",["li",["a",{className:"bisheng-toc-h2",href:"#zh-CN",title:"zh-CN"},"zh-CN"]],["li",["a",{className:"bisheng-toc-h2",href:"#en-US",title:"en-US"},"en-US"]]],highlightedCode:["pre",{lang:"jsx",highlighted:`<span class="token keyword">import</span> <span class="token punctuation">{</span> IconPro <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pmbase'</span>

ReactDOM<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span>
  <span class="token operator">&lt;</span>IconPro  type<span class="token operator">=</span><span class="token string">"icon-xiazai"</span> scriptUrl <span class="token operator">=</span> <span class="token string">'//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js'</span><span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">,</span>
  mountNode<span class="token punctuation">)</span><span class="token punctuation">;</span>`}],highlightedCodes:{jsx:`<span class="token keyword">import</span> <span class="token punctuation">{</span> IconPro <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'pmbase'</span>

ReactDOM<span class="token punctuation">.</span><span class="token function">render</span><span class="token punctuation">(</span>
  <span class="token operator">&lt;</span>IconPro  type<span class="token operator">=</span><span class="token string">"icon-xiazai"</span> scriptUrl <span class="token operator">=</span> <span class="token string">'//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js'</span><span class="token operator">/</span><span class="token operator">></span><span class="token punctuation">,</span>
  mountNode<span class="token punctuation">)</span><span class="token punctuation">;</span>`},preview:function(){var t=n(0),e=n(48),o=n(2991);return t.createElement(o.IconPro,{type:"icon-xiazai",scriptUrl:"//at.alicdn.com/t/font_8d5l8fzk5b87iudi.js"})}}}}]);
